config/routes.rb
SriProj::Application.routes.draw do
 
  root to: "users#index"
  get 'login', to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

  resources :bookings

  resources :classrooms

  resources :courses

  resources :locations

  resources :programs

  resources :periods

  resources :teaching_assignments

  resources :cohorts

  resources :enrollments

  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? :producer
      can :manage, :all
    elsif 
      can :read, Program
    end
  end




end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :period_id, :cohort_id, :classroom_id,:period, :cohort, :classroom
  belongs_to :classroom
  belongs_to :period
  belongs_to :cohort
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :facilities, :name, :size, :location_id, :period_id, :location, :period
  belongs_to :location
  belongs_to :period
  has_many :bookings
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :course_id, :course, :iteration

  has_many :teaching_assignments
  has_many :instructors, through: :teaching_assignments

  belongs_to :course
  
  has_many :bookings

  has_many :enrollments
  has_many :students, through: :enrollments

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :iteration, :name, :location_id, :program_id, :producer_id, :location, :program, :producer

  has_many :cohorts
  belongs_to :location
  belongs_to :producer, class_name: "User", foreign_key: :producer_id
  belongs_to :program


end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  attr_accessible :enrollment_date, :has_paid, :prework_done, :student, :student_id, :cohort, :cohort_id

  belongs_to :student, class_name: "User", foreign_key: :student_id
  belongs_to :cohort  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  has_many :classrooms
  has_many :courses
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :slot
  has_many :classrooms
  has_many :bookings
  
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :name, :longname
  has_many :courses
end

app/models/teaching_assignment.rb
class TeachingAssignment < ActiveRecord::Base
  attr_accessible :assign_date, :rate, :cohort_id, :instructor_id, :cohort, :instructor
  belongs_to :instructor, class_name: "User", foreign_key: :instructor_id
  belongs_to :cohort
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true


  attr_accessible :email, :firstname, :lastname, :role, :password, :password_confirmation, :password_digest

  has_many :enrollments, foreign_key: :student_id
  has_many :cohorts_memberships, through: :enrollments, source: :cohort
    
  has_many :teaching_assignments, foreign_key: :instructor_id
  has_many :taught_cohorts, through: :teaching_assignments, source: :cohort

  has_many :courses, foreign_key: :producer_id

  def role?(role)
  self.role.to_s == role.to_s
  end

end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  def index
    @cohorts = Cohort.all

    
  end

  def show
    @cohort = Cohort.find(params[:id])

    
  end

  def new
    @cohort = Cohort.new

    
  end

  def edit
    @cohort = Cohort.find(params[:id])
  end


  def create

    puts "LOOKING AT PARAMS"
    puts "#{params.to_s}"
render :text => "hello"
    @cohort = Cohort.new(params[:cohort])
 
  end

  def update
    @cohort = Cohort.find(params[:id])

    
  end


  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy

    
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

      # def collectionOfRolesHash
      #   collRoles = {:student => "student", :instructor => "instructor", 
      #               :producer => "producer", :regional => "regional",
      #               :admin => "admin"
      #               }
      # end

      # def collectionOfRolesHash
      #   collRoles = {:student => "student", :instructor => "instructor", 
      #               :producer => "producer", :regional => "regional",
      #               :admin => "admin"
      #               }
      #   collRoles = ["student", "instructor","producer","regional" ]
      # end


    # def listofPrograms
    #     Program.all.map{ |p| p.name }
    # end

    # def listofLocations
    #   Location.all.map{ |l| l.name  }
    # end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper







end

app/views/cohorts/_form.html.erb
<%= form_for(@cohort) do |f| %>
  <% if @cohort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cohort.errors.count, "error") %> prohibited this cohort from being saved:</h2>

      <ul>
      <% @cohort.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <p>Hi!!!</p>

  <p>Type of program?</p>





  <%= f.number_field :iteration %>
 

 
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  
  <div class="field">
    <%= f.label "Give it a name?" %><br />
    <%= f.text_field :start_date %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cohorts/edit.html.erb
<h1>Editing cohort</h1>

<%= render 'form' %>

<%= link_to 'Show', @cohort %> |
<%= link_to 'Back', cohorts_path %>

app/views/cohorts/index.html.erb
<h1>Listing cohorts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cohorts.each do |cohort| %>
  <tr>
    <td><%= cohort.name %></td>
    <td><%= cohort.start_date %></td>
    <td><%= cohort.end_date %></td>
    <td><%= link_to 'Show', cohort %></td>
    <td><%= link_to 'Edit', edit_cohort_path(cohort) %></td>
    <td><%= link_to 'Destroy', cohort, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cohort', new_cohort_path %>

app/views/cohorts/new.html.erb
<h1>New cohort</h1>

<%= render 'form' %>

<%= link_to 'Back', cohorts_path %>

app/views/cohorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cohort.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @cohort.start_date %>
</p>

<p>
  <b>Start date:</b>
  <%= @cohort.start_date %>
</p>


<p>
  <b>End date:</b>
  <%= @cohort.end_date %>
</p>


<% for student in @cohort.students %>
    <div class="student">
     
      
        <%= link_to student.firstname, student %>
     
        
      </div>
         <br/>
      
  <% end %>






<%= link_to 'Edit', edit_cohort_path(@cohort) %> |
<%= link_to 'Back', cohorts_path %>