config/routes.rb
SriProj::Application.routes.draw do
 
  root to: "users#index"
  get 'login', to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

  resources :bookings

  resources :classrooms

  resources :courses

  resources :locations

  resources :programs

  resources :periods

  resources :teaching_assignments

  resources :cohorts

  resources :enrollments

  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? :producer
      can :manage, :all
    elsif 
      can :read, Program
    end
  end




end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :period_id, :cohort_id, :classroom_id,:period, :cohort, :classroom
  belongs_to :classroom
  belongs_to :period
  belongs_to :cohort
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :facilities, :name, :size, :location_id, :period_id, :location, :period
  belongs_to :location
  belongs_to :period
  has_many :bookings
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :course_id, :course, :iteration

  has_many :teaching_assignments
  has_many :instructors, through: :teaching_assignments

  belongs_to :course
  
  has_many :bookings

  has_many :enrollments
  has_many :students, through: :enrollments

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :iteration, :name, :location_id, :program_id, :producer_id, :location, :program, :producer

  has_many :cohorts
  belongs_to :location
  belongs_to :producer, class_name: "User", foreign_key: :producer_id
  belongs_to :program


end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  attr_accessible :enrollment_date, :has_paid, :prework_done, :student, :student_id, :cohort, :cohort_id

  belongs_to :student, class_name: "User", foreign_key: :student_id
  belongs_to :cohort  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  has_many :classrooms
  has_many :courses
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :slot
  has_many :classrooms
  has_many :bookings
  
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :name, :longname
  has_many :courses
end

app/models/teaching_assignment.rb
class TeachingAssignment < ActiveRecord::Base
  attr_accessible :assign_date, :rate, :cohort_id, :instructor_id, :cohort, :instructor
  belongs_to :instructor, class_name: "User", foreign_key: :instructor_id
  belongs_to :cohort
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true


  attr_accessible :email, :firstname, :lastname, :role, :password, :password_confirmation, :password_digest

  has_many :enrollments, foreign_key: :student_id
  has_many :cohorts_memberships, through: :enrollments, source: :cohort
    
  has_many :teaching_assignments, foreign_key: :instructor_id
  has_many :taught_cohorts, through: :teaching_assignments, source: :cohort

  has_many :courses, foreign_key: :producer_id

  def role?(role)
  self.role.to_s == role.to_s
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookings }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.json
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render json: @booking, status: :created, location: @booking }
      else
        format.html { render action: "new" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.json
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

      # def collectionOfRolesHash
      #   collRoles = {:student => "student", :instructor => "instructor", 
      #               :producer => "producer", :regional => "regional",
      #               :admin => "admin"
      #               }
      # end

      # def collectionOfRolesHash
      #   collRoles = {:student => "student", :instructor => "instructor", 
      #               :producer => "producer", :regional => "regional",
      #               :admin => "admin"
      #               }
      #   collRoles = ["student", "instructor","producer","regional" ]
      # end


    # def listofPrograms
    #     Program.all.map{ |p| p.name }
    # end

    # def listofLocations
    #   Location.all.map{ |l| l.name  }
    # end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper







end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.start_date %></td>
    <td><%= booking.end_date %></td>
    <td><%= link_to 'Show', booking %></td>
    <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
    <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start date:</b>
  <%= @booking.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @booking.end_date %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>