config/routes.rb
SriProj::Application.routes.draw do
 
  root to: "users#index"
  get 'login', to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

  resources :bookings

  resources :classrooms

  resources :courses

  resources :locations

  resources :programs

  resources :periods

  resources :teaching_assignments

  resources :cohorts

  resources :enrollments

  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? :producer
      can :manage, :all
    elsif 
      can :read, Program
    end
  end




end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :period_id, :cohort_id, :classroom_id,:period, :cohort, :classroom
  belongs_to :classroom
  belongs_to :period
  belongs_to :cohort
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :facilities, :name, :size, :location_id, :period_id, :location, :period
  belongs_to :location
  belongs_to :period
  has_many :bookings
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :course_id, :course, :iteration

  has_many :teaching_assignments
  has_many :instructors, through: :teaching_assignments

  belongs_to :course
  
  has_many :bookings

  has_many :enrollments
  has_many :students, through: :enrollments

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :iteration, :name, :location_id, :program_id, :producer_id, :location, :program, :producer

  has_many :cohorts
  belongs_to :location
  belongs_to :producer, class_name: "User", foreign_key: :producer_id
  belongs_to :program


end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  attr_accessible :enrollment_date, :has_paid, :prework_done, :student, :student_id, :cohort, :cohort_id

  belongs_to :student, class_name: "User", foreign_key: :student_id
  belongs_to :cohort  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  has_many :classrooms
  has_many :courses
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :slot
  has_many :classrooms
  has_many :bookings
  
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :name, :longname
  has_many :courses
end

app/models/teaching_assignment.rb
class TeachingAssignment < ActiveRecord::Base
  attr_accessible :assign_date, :rate, :cohort_id, :instructor_id, :cohort, :instructor
  belongs_to :instructor, class_name: "User", foreign_key: :instructor_id
  belongs_to :cohort
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true


  attr_accessible :email, :firstname, :lastname, :role, :password, :password_confirmation, :password_digest

  has_many :enrollments, foreign_key: :student_id
  has_many :cohorts_memberships, through: :enrollments, source: :cohort
    
  has_many :teaching_assignments, foreign_key: :instructor_id
  has_many :taught_cohorts, through: :teaching_assignments, source: :cohort

  has_many :courses, foreign_key: :producer_id

  def role?(role)
  self.role.to_s == role.to_s
  end

end

app/controllers/teaching_assignments_controller.rb
class TeachingAssignmentsController < ApplicationController
  # GET /teaching_assignments
  # GET /teaching_assignments.json
  def index
    @teaching_assignments = TeachingAssignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teaching_assignments }
    end
  end

  # GET /teaching_assignments/1
  # GET /teaching_assignments/1.json
  def show
    @teaching_assignment = TeachingAssignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teaching_assignment }
    end
  end

  # GET /teaching_assignments/new
  # GET /teaching_assignments/new.json
  def new
    @teaching_assignment = TeachingAssignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teaching_assignment }
    end
  end

  # GET /teaching_assignments/1/edit
  def edit
    @teaching_assignment = TeachingAssignment.find(params[:id])
  end

  # POST /teaching_assignments
  # POST /teaching_assignments.json
  def create
    @teaching_assignment = TeachingAssignment.new(params[:teaching_assignment])

    respond_to do |format|
      if @teaching_assignment.save
        format.html { redirect_to @teaching_assignment, notice: 'Teaching assignment was successfully created.' }
        format.json { render json: @teaching_assignment, status: :created, location: @teaching_assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @teaching_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teaching_assignments/1
  # PUT /teaching_assignments/1.json
  def update
    @teaching_assignment = TeachingAssignment.find(params[:id])

    respond_to do |format|
      if @teaching_assignment.update_attributes(params[:teaching_assignment])
        format.html { redirect_to @teaching_assignment, notice: 'Teaching assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teaching_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teaching_assignments/1
  # DELETE /teaching_assignments/1.json
  def destroy
    @teaching_assignment = TeachingAssignment.find(params[:id])
    @teaching_assignment.destroy

    respond_to do |format|
      format.html { redirect_to teaching_assignments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

      # def collectionOfRolesHash
      #   collRoles = {:student => "student", :instructor => "instructor", 
      #               :producer => "producer", :regional => "regional",
      #               :admin => "admin"
      #               }
      # end

      # def collectionOfRolesHash
      #   collRoles = {:student => "student", :instructor => "instructor", 
      #               :producer => "producer", :regional => "regional",
      #               :admin => "admin"
      #               }
      #   collRoles = ["student", "instructor","producer","regional" ]
      # end


    # def listofPrograms
    #     Program.all.map{ |p| p.name }
    # end

    # def listofLocations
    #   Location.all.map{ |l| l.name  }
    # end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teaching_assignments_helper.rb
module TeachingAssignmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper







end

app/views/teaching_assignments/_form.html.erb
<%= form_for(@teaching_assignment) do |f| %>
  <% if @teaching_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teaching_assignment.errors.count, "error") %> prohibited this teaching_assignment from being saved:</h2>

      <ul>
      <% @teaching_assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :assign_date %><br />
    <%= f.date_select :assign_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teaching_assignments/edit.html.erb
<h1>Editing teaching_assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @teaching_assignment %> |
<%= link_to 'Back', teaching_assignments_path %>

app/views/teaching_assignments/index.html.erb
<h1>Listing teaching_assignments</h1>

<table>
  <tr>
    <th>Rate</th>
    <th>Assign date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teaching_assignments.each do |teaching_assignment| %>
  <tr>
    <td><%= teaching_assignment.rate %></td>
    <td><%= teaching_assignment.assign_date %></td>
    <td><%= link_to 'Show', teaching_assignment %></td>
    <td><%= link_to 'Edit', edit_teaching_assignment_path(teaching_assignment) %></td>
    <td><%= link_to 'Destroy', teaching_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Teaching assignment', new_teaching_assignment_path %>

app/views/teaching_assignments/new.html.erb
<h1>New teaching_assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', teaching_assignments_path %>

app/views/teaching_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rate:</b>
  <%= @teaching_assignment.rate %>
</p>

<p>
  <b>Assign date:</b>
  <%= @teaching_assignment.assign_date %>
</p>


<%= link_to 'Edit', edit_teaching_assignment_path(@teaching_assignment) %> |
<%= link_to 'Back', teaching_assignments_path %>