config/routes.rb
SriProj::Application.routes.draw do
 
  root to: "users#index"
  get 'login', to: 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]

  resources :bookings

  resources :classrooms

  resources :courses

  resources :locations

  resources :programs

  resources :periods

  resources :teaching_assignments

  resources :cohorts

  resources :enrollments

  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role? :producer
      can :manage, :all
    elsif 
      can :read, Program
    end
  end




end

app/models/booking.rb
class Booking < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :period_id, :cohort_id, :classroom_id,:period, :cohort, :classroom
  belongs_to :classroom
  belongs_to :period
  belongs_to :cohort
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  attr_accessible :facilities, :name, :size, :location_id, :period_id, :location, :period
  belongs_to :location
  belongs_to :period
  has_many :bookings
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :course_id, :course, :iteration

  has_many :teaching_assignments
  has_many :instructors, through: :teaching_assignments

  belongs_to :course
  
  has_many :bookings

  has_many :enrollments
  has_many :students, through: :enrollments

end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :iteration, :name, :location_id, :program_id, :producer_id, :location, :program, :producer

  has_many :cohorts
  belongs_to :location
  belongs_to :producer, class_name: "User", foreign_key: :producer_id
  belongs_to :program


end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  attr_accessible :enrollment_date, :has_paid, :prework_done, :student, :student_id, :cohort, :cohort_id

  belongs_to :student, class_name: "User", foreign_key: :student_id
  belongs_to :cohort  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  has_many :classrooms
  has_many :courses
end

app/models/period.rb
class Period < ActiveRecord::Base
  attr_accessible :slot
  has_many :classrooms
  has_many :bookings
  
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :name, :longname
  has_many :courses
end

app/models/teaching_assignment.rb
class TeachingAssignment < ActiveRecord::Base
  attr_accessible :assign_date, :rate, :cohort_id, :instructor_id, :cohort, :instructor
  belongs_to :instructor, class_name: "User", foreign_key: :instructor_id
  belongs_to :cohort
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true


  attr_accessible :email, :firstname, :lastname, :role, :password, :password_confirmation, :password_digest

  has_many :enrollments, foreign_key: :student_id
  has_many :cohorts_memberships, through: :enrollments, source: :cohort
    
  has_many :teaching_assignments, foreign_key: :instructor_id
  has_many :taught_cohorts, through: :teaching_assignments, source: :cohort

  has_many :courses, foreign_key: :producer_id

  def role?(role)
  self.role.to_s == role.to_s
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enrollments }
    end
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
    @enrollment = Enrollment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enrollment }
    end
  end

  # GET /enrollments/new
  # GET /enrollments/new.json
  def new
    @enrollment = Enrollment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enrollment }
    end
  end

  # GET /enrollments/1/edit
  def edit
    @enrollment = Enrollment.find(params[:id])
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(params[:enrollment])

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render json: @enrollment, status: :created, location: @enrollment }
      else
        format.html { render action: "new" }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enrollments/1
  # PUT /enrollments/1.json
  def update
    @enrollment = Enrollment.find(params[:id])

    respond_to do |format|
      if @enrollment.update_attributes(params[:enrollment])
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment = Enrollment.find(params[:id])
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

      # def collectionOfRolesHash
      #   collRoles = {:student => "student", :instructor => "instructor", 
      #               :producer => "producer", :regional => "regional",
      #               :admin => "admin"
      #               }
      # end

      # def collectionOfRolesHash
      #   collRoles = {:student => "student", :instructor => "instructor", 
      #               :producer => "producer", :regional => "regional",
      #               :admin => "admin"
      #               }
      #   collRoles = ["student", "instructor","producer","regional" ]
      # end


    # def listofPrograms
    #     Program.all.map{ |p| p.name }
    # end

    # def listofLocations
    #   Location.all.map{ |l| l.name  }
    # end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper







end

app/views/enrollments/_form.html.erb
<%= form_for(@enrollment) do |f| %>
  <% if @enrollment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
      <% @enrollment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prework_done %><br />
    <%= f.check_box :prework_done %>
  </div>
  <div class="field">
    <%= f.label :has_paid %><br />
    <%= f.check_box :has_paid %>
  </div>
  <div class="field">
    <%= f.label :enrollment_date %><br />
    <%= f.date_select :enrollment_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render 'form' %>

<%= link_to 'Show', @enrollment %> |
<%= link_to 'Back', enrollments_path %>

app/views/enrollments/index.html.erb
<h1>Listing enrollments</h1>

<table>
  <tr>
    <th>Prework done</th>
    <th>Has paid</th>
    <th>Enrollment date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enrollments.each do |enrollment| %>
  <tr>
    <td><%= enrollment.prework_done %></td>
    <td><%= enrollment.has_paid %></td>
    <td><%= enrollment.enrollment_date %></td>
    <td><%= link_to 'Show', enrollment %></td>
    <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
    <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render 'form' %>

<%= link_to 'Back', enrollments_path %>

app/views/enrollments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prework done:</b>
  <%= @enrollment.prework_done %>
</p>

<p>
  <b>Has paid:</b>
  <%= @enrollment.has_paid %>
</p>

<p>
  <b>Enrollment date:</b>
  <%= @enrollment.enrollment_date %>
</p>


<%= link_to 'Edit', edit_enrollment_path(@enrollment) %> |
<%= link_to 'Back', enrollments_path %>